import { orBlank, type Company } from "./company";

/**
 * A política e os termos que a loja publica, escritos a partir do que o exame
 * viu nela.
 *
 * Generated by code and never by a model, and the reason is the same one that
 * keeps a model out of the findings (ADR-0001): this text goes on somebody's
 * storefront as their own legal document, and a sentence that changes between
 * two runs over the same shop is a sentence nobody can review. Everything here
 * is a template plus facts — the company the owner typed, and the services the
 * browser observed.
 *
 * The one thing that makes it worth generating at all is section 2 of the
 * policy: it names the services this shop actually runs, taken from the
 * reading, not a list of the usual suspects. That naming is what the audit
 * keeps finding missing, and what article 9º, V asks for.
 */

/** Which document this is. Mirrors `documents.kind` in the database. */
export type DocumentKind = "privacy_policy" | "terms_of_use";

export const KINDS: Record<DocumentKind, string> = {
  privacy_policy: "Política de Privacidade",
  terms_of_use: "Termos de Uso",
};

/** A service the reading found, and what it is there for. */
export type NamedTracker = {
  name: string;
  purpose: "essential" | "analytics" | "marketing";
};

export type DocumentInput = {
  /** The store's address, as the document names it. */
  host: string;
  company: Company;
  /** The services the reading found, named. */
  trackers: readonly NamedTracker[];
  /** When the reading that named them happened. */
  readAt: Date | null;
  /** When this document is being generated. */
  at: Date;
};

const DAY = new Intl.DateTimeFormat("pt-BR", {
  day: "numeric",
  month: "long",
  year: "numeric",
});

/** "a, b e c" — the list as somebody would say it out loud. */
function listed(names: readonly string[]): string {
  if (names.length <= 1) return names[0] ?? "";
  return `${names.slice(0, -1).join(", ")} e ${names[names.length - 1]}`;
}

const withPurpose = (
  trackers: readonly NamedTracker[],
  purpose: NamedTracker["purpose"]
) =>
  [
    ...new Set(
      trackers.filter((t) => t.purpose === purpose).map(({ name }) => name)
    ),
  ].sort();

/**
 * The section the whole product exists to be able to write.
 *
 * Article 9º, V asks that the person be told who their data is shared with, and
 * the audit's commonest finding is a policy that says "parceiros" and names
 * nobody. So this names them, one by one, split by what they are for — which is
 * also what makes the consent banner's own categories legible when somebody
 * reads both.
 *
 * A shop where the reading found nothing gets a sentence saying so, not an
 * empty heading. "Nenhum serviço de terceiro foi observado" is a fact about a
 * reading, and it is dated in the line above it.
 */
function services(input: DocumentInput): string {
  const analytics = withPurpose(input.trackers, "analytics");
  const marketing = withPurpose(input.trackers, "marketing");
  const essential = withPurpose(input.trackers, "essential");

  if (input.trackers.length === 0) {
    return "No exame que originou este documento, nosso navegador não observou serviços de terceiros gravando cookies ou recebendo dados sobre a navegação nesta loja.";
  }

  const paragraphs: string[] = [];

  if (marketing.length > 0) {
    paragraphs.push(
      `**Publicidade e mensuração de campanhas.** ${listed(marketing)}. Esses serviços podem gravar cookies no seu navegador e receber informações sobre a sua navegação para exibir anúncios e medir o resultado deles. Eles dependem do seu consentimento e permanecem desativados até que você o dê.`
    );
  }

  if (analytics.length > 0) {
    paragraphs.push(
      `**Medição de audiência.** ${listed(analytics)}. Esses serviços registram como esta loja é usada — páginas visitadas, tempo de permanência, origem do acesso — para que possamos melhorá-la. Eles dependem do seu consentimento e permanecem desativados até que você o dê.`
    );
  }

  if (essential.length > 0) {
    paragraphs.push(
      `**Necessários para a loja funcionar.** ${listed(essential)}. Sem eles a loja não opera, e por isso não dependem de consentimento.`
    );
  }

  return paragraphs.join("\n\n");
}

/** The line that says what this document was written from. */
function basedOn(input: DocumentInput): string {
  return input.readAt
    ? `Os serviços nomeados na seção 2 foram observados no exame desta loja realizado em ${DAY.format(input.readAt)}.`
    : "Os serviços nomeados na seção 2 foram observados em exame desta loja.";
}

export function privacyPolicy(input: DocumentInput): string {
  const { company, host } = input;
  const contact = orBlank(company.email);

  return `# Política de Privacidade

Esta política descreve como a loja **${host}** trata os dados pessoais de quem
navega por ela, para que finalidades, por quanto tempo e com quem esses dados
são compartilhados. Ela foi atualizada em ${DAY.format(input.at)}.

## 1. Quem trata os seus dados

O controlador dos dados pessoais tratados nesta loja é
**${orBlank(company.legalName)}**, inscrita no CNPJ ${orBlank(company.cnpj)},
com sede em ${orBlank(company.address)}.

## 2. O que é coletado quando você navega

Ao visitar esta loja, além dos dados que você mesmo informa — como nome, e-mail,
endereço e dados de pagamento ao concluir uma compra — os serviços de terceiros
abaixo podem gravar cookies no seu navegador ou receber informações sobre a sua
navegação.

${services(input)}

${basedOn(input)}

## 3. Cookies e consentimento

Cookies que dependem de consentimento permanecem desativados até que você
responda ao banner exibido na sua primeira visita. Você pode aceitar todos,
recusar todos, ou escolher por finalidade.

Recusar não impede o uso desta loja: os cookies necessários para o
funcionamento — sessão, carrinho e segurança do formulário — continuam
funcionando, porque sem eles a loja não opera.

## 4. Como revogar o seu consentimento

Você pode **revogar** o consentimento a qualquer momento, com a mesma
facilidade com que o deu, pelo link de preferências de cookies disponível no
rodapé desta loja. A revogação vale a partir do momento em que é feita e não
afeta os tratamentos realizados antes dela.

## 5. Com quem os dados são compartilhados

Os dados são compartilhados com os serviços nomeados na seção 2, nos limites
descritos ali, e com os prestadores necessários para concluir a sua compra —
meio de pagamento, transportadora e emissor de nota fiscal. Não vendemos dados
pessoais.

## 6. Por quanto tempo os dados são guardados

Os dados de cadastro e de compra são guardados enquanto durar a relação de
consumo e pelos prazos que a legislação fiscal e o Código de Defesa do
Consumidor exigem. Os cookies têm prazo próprio, informado no banner de
consentimento.

## 7. Os seus direitos como titular

A Lei nº 13.709 (LGPD), no artigo 18, garante a você o direito de pedir, a
qualquer momento: a confirmação da existência de tratamento; o acesso aos seus
dados; a correção de dados incompletos, inexatos ou desatualizados; a
anonimização, o bloqueio ou a eliminação de dados desnecessários ou tratados
fora da lei; a portabilidade a outro fornecedor; a eliminação dos seus dados
tratados com base no consentimento; a informação sobre com quem compartilhamos
os seus dados; e a revogação do consentimento.

Para exercer qualquer um deles, escreva para ${contact}.

## 8. Encarregado pelo tratamento de dados

O encarregado (DPO) desta loja é ${orBlank(company.officer)}, que pode ser
contatado em ${orBlank(company.officerEmail)}.

## 9. Contato

Dúvidas sobre esta política podem ser enviadas para ${contact}.

## 10. Alterações desta política

Quando esta política mudar, a versão nova passa a valer a partir da data de
atualização informada no topo. As versões anteriores continuam disponíveis
mediante pedido pelo contato acima.
`;
}

/**
 * Os termos, deliberadamente mais curtos que a política.
 *
 * A privacy policy can be written from what the browser measured; terms of use
 * cannot. What a shop sells, how it ships, what it charges and what it promises
 * are facts nobody here knows, and a generated paragraph inventing them would
 * be worse than no paragraph at all. So this covers what is the same for every
 * Brazilian shop — who the supplier is, the seven-day right of regret the CDC
 * grants, the forum — and marks the rest for the owner to write.
 */
export function termsOfUse(input: DocumentInput): string {
  const { company, host } = input;

  return `# Termos de Uso

Estes termos regem o uso da loja **${host}** e a compra de produtos por ela.
Ao navegar ou comprar, você concorda com eles. Foram atualizados em
${DAY.format(input.at)}.

## 1. Quem é o fornecedor

Esta loja é operada por **${orBlank(company.legalName)}**, inscrita no CNPJ
${orBlank(company.cnpj)}, com sede em ${orBlank(company.address)}, a quem você
pode escrever em ${orBlank(company.email)}.

## 2. Cadastro

Para comprar, você informa os dados necessários à entrega e à emissão da nota
fiscal, e é responsável por mantê-los corretos. Os dados informados são tratados
conforme a Política de Privacidade desta loja.

## 3. Produtos, preços e disponibilidade

As descrições, preços e prazos exibidos valem para o momento da compra. Erros
evidentes de preço ou de descrição podem levar ao cancelamento do pedido, com
devolução integral do valor pago.

## 4. Pagamento e entrega

As formas de pagamento e os prazos de entrega são os exibidos no momento da
compra. O prazo começa a contar da confirmação do pagamento.

## 5. Direito de arrependimento

O artigo 49 do Código de Defesa do Consumidor garante a você **sete dias
corridos**, contados do recebimento, para desistir da compra feita fora do
estabelecimento comercial, sem precisar justificar. Os valores pagos são
devolvidos integralmente.

## 6. Trocas e devoluções por defeito

Produto com defeito segue os prazos do Código de Defesa do Consumidor: trinta
dias para produtos não duráveis e noventa dias para duráveis, contados do
recebimento ou da constatação do defeito.

## 7. Propriedade intelectual

O conteúdo desta loja — textos, imagens, marcas e código — pertence a
${orBlank(company.legalName)} ou a quem lhe licenciou o uso, e não pode ser
reproduzido sem autorização.

## 8. Condições específicas desta loja

${orBlank("")} — descreva aqui o que é próprio do seu negócio e não cabe nas
cláusulas acima: regras de frete, condições promocionais, restrições de entrega
por região, garantias além das legais.

## 9. Foro

Fica eleito o foro do domicílio do consumidor para dirimir questões decorrentes
destes termos, conforme o Código de Defesa do Consumidor.
`;
}

/** The document of this kind, written out. */
export function generate(kind: DocumentKind, input: DocumentInput): string {
  return kind === "privacy_policy" ? privacyPolicy(input) : termsOfUse(input);
}
