export const content = {
  pt: {
    hero: {
      navCta: "Entrar na lista →",
      badge: "Em desenvolvimento — entre na lista de espera",
      h1Line1: "Seu usuário achou o bug.",
      h1Line2: "Você recebe o replay.",
      sub: "Cole um script no seu SaaS em 30 segundos. Cada report chega com Replay da Interação do seu usuário, sessão gravada, logs de rede e console —",
      subHighlight: "sem ida e volta.",
      cta: "Quero acesso antecipado",
      widgetCardLabel: "Para seu site",
      widgetDesc: "Simule o fluxo completo — clique em",
      widgetDescBold: "Enviar report",
      widgetDescSuffix: "no widget e veja como um bug vira ticket com replay e logs em segundos.",
      ticketEyebrow: "É assim que vai ficar seu ticket no",
      ticketEyebrowBold: "dashboard",
      ticketStatus: "aberto",
      ticketTitle: "Página de Checkout",
      ticketMeta: "20 de fev. de 2026 às 14:32:07 · via BugSniff widget · seusite.com.br",
      replayLabel: "Replay da sessão",
      replayMeta: "42 frames · 00:42 · silencioso",
      timelineLabel: "Timeline",
      logsLabel: "Logs",
      consoleLabel: "Console",
      ticketLogTexts: [
        "→  Navegou para /checkout",
        "↖  Clique em 'Finalizar compra'",
        "⇅  GET /api/user · 200 OK",
        "⇅  GET /api/cart · 200 OK",
        "⇅  POST /api/apply-coupon · 206 Partial",
        "⇅  POST /api/checkout · 422 Unprocessable",
        "✕  TypeError: Cannot read properties of undefined (reading 'id')",
        "✕  Uncaught error in event handler",
      ],
    },
    howItWorks: {
      title: "Como funciona",
      subtitle: "Dois caminhos, um dashboard. Escolha o que faz mais sentido — ou use os dois.",
      scriptBadge: "<script>",
      scriptTitle: "Para seu site",
      testerBadge: "Chrome",
      testerTitle: "Para seus testers",
      scriptSteps: [
        { n: "01", title: "Cola o script", desc: "Uma linha de código no seu HTML. Zero configuração adicional." },
        { n: "02", title: "Visitante vê o widget", desc: 'Um botão flutuante aparece no canto da tela: "Reportar bug".' },
        { n: "03", title: "Reporta com contexto", desc: "Replay da sessão, logs de rede e console são capturados automaticamente." },
        { n: "04", title: "Ticket no dashboard", desc: "Dev abre o ticket e reproduz o bug na primeira tentativa." },
      ],
      testerSteps: [
        { n: "01", title: "Instala a extensão", desc: "Extensão Chrome disponível como .zip — sem precisar da Chrome Store." },
        { n: "02", title: "Cola a API key", desc: "Dev gera a key no dashboard e envia para o tester. Configuração em 30s." },
        { n: "03", title: "Navega e reporta", desc: "Grava a sessão completa. Seleciona o trecho do bug na timeline." },
        { n: "04", title: "Ticket no dashboard", desc: "rrweb replay, network logs, console logs e metadata chegam juntos." },
      ],
    },
    problem: {
      title: "O bug chega. O contexto, não.",
      subtitle: "Tester clica, dev não vê. O ciclo come horas de desenvolvimento que poderiam ir para features.",
      soundFamiliar: "Soa familiar?",
      stats: [
        { value: "30%", label: "dos bugs reportados", desc: "não são reproduzíveis pelo dev que recebe o report." },
        { value: "3×", label: "mais tempo de fix", desc: "quando o report chega sem logs de rede e console." },
        { value: "2–4h", label: "por sprint desperdiçadas", desc: 'em loops de "não consigo reproduzir" entre dev e tester.' },
      ],
      painPoints: [
        '"Não consigo reproduzir esse bug"',
        '"Qual versão do browser você estava usando?"',
        '"Pode gravar um vídeo e mandar?"',
        '"Que chamada de API estava fazendo?"',
        '"Qual era o erro no console?"',
        '"Pode me dar os passos exatos para reproduzir?"',
      ],
    },
    dashboard: {
      title: "O que chega no dashboard",
      subtitle: "Cada ticket tem tudo que o dev precisa para reproduzir e corrigir — sem perguntar mais nada.",
      ticketTitle: "Checkout quebrado após seleção de endereço",
      replayLabel: "Replay",
      timelineLabel: "Timeline de eventos",
      networkLabel: "Network logs",
      consoleLabel: "Console logs",
      metaLabel: "Metadata",
      metaRows: [
        ["Browser", "Chrome 131 / macOS 14"],
        ["Viewport", "1440 × 900"],
        ["URL", "/checkout?step=2"],
        ["Reportado", "há 3 minutos"],
      ],
      timelineEvents: [
        { type: "click", label: "Clique em 'Finalizar compra'", t: "00:38" },
        { type: "network", label: "POST /api/checkout → 422", t: "00:39" },
        { type: "error", label: "TypeError: Cannot read 'id'", t: "00:39" },
        { type: "network", label: "GET /api/payment → 500", t: "00:40" },
        { type: "click", label: "Clique em 'Tentar novamente'", t: "00:42" },
      ],
    },
    cta: {
      title: 'Chega de "não consigo reproduzir"',
      subtitle:
        "BugSniff está em desenvolvimento. Entre na lista de espera e seja avisado quando abrir o acesso — e ajude a moldar o produto com seu feedback.",
      button: "Entrar na lista de espera",
    },
    footer: {
      waitlist: "Lista de espera",
      email: "contato@bugsniff.com.br",
    },
    modal: {
      title: "Entrar na lista de espera",
      subtitle: "Te avisamos quando o BugSniff abrir.",
      successTitle: "Você está na lista!",
      successDesc: "Te avisamos por email assim que o BugSniff abrir.\nObrigado pelo interesse!",
      closeBtn: "Fechar",
      emailLabel: "Email",
      feedbackLabel: "Qual seu maior desafio com bugs?",
      feedbackOptional: "(opcional)",
      emailPlaceholder: "voce@empresa.com",
      feedbackPlaceholder: "Ex: testers não conseguem descrever o contexto, bugs não reproduzíveis...",
      submitBtn: "Me avise quando estiver pronto",
      submittingBtn: "Enviando...",
      noSpam: "Sem spam. Apenas um aviso quando o produto abrir.",
      closeLabel: "Fechar",
      errorFallback: "Algo deu errado. Tente novamente.",
      errorConnection: "Erro de conexão. Verifique sua internet e tente novamente.",
    },
    widget: {
      hint: "clique e simule o fluxo",
      openTitle: "Fechar widget",
      closedTitle: "Abrir widget",
      readyLabel: "— pronto para capturar",
      reportPlaceholder: "Ex: Botão não funciona ao fazer checkout…",
      sendBtn: "Enviar report",
      capturingLabel: "Capturando screenshots…",
      capturingSub: "montando replay silencioso",
      replayCaptured: "Replay capturado",
      replayMeta: "silencioso · 42 frames",
      timelineLabel: "Timeline",
      logsLabel: "Logs",
      creatingLabel: "Criando ticket…",
      creatingSub: "anexando replay e logs",
      ticketLabel: "Página de Checkout",
      sendTicketBtn: "Enviar",
      ticketCreated: "Ticket criado!",
      ticketRef: "#tkt_7f2a · Página de Checkout",
      ticketNote: "Replay silencioso anexado automaticamente",
      logLabels: ["Clique no checkout", "TypeError: Cannot read 'id'", "POST /api/checkout 422"],
    },
  },

  en: {
    hero: {
      navCta: "Join the waitlist →",
      badge: "In development — join the waitlist",
      h1Line1: "Your user found the bug.",
      h1Line2: "You get the replay.",
      sub: "Drop a script into your SaaS in 30 seconds. Every bug report comes with a session replay, network and console logs —",
      subHighlight: "no back-and-forth.",
      cta: "Get early access",
      widgetCardLabel: "For your site",
      widgetDesc: "Try the full flow — click",
      widgetDescBold: "Send report",
      widgetDescSuffix: "in the widget and see how a bug becomes a ticket with replay and logs in seconds.",
      ticketEyebrow: "Here's how your ticket looks in the",
      ticketEyebrowBold: "dashboard",
      ticketStatus: "open",
      ticketTitle: "Checkout Page",
      ticketMeta: "Feb 20, 2026 at 14:32:07 · via BugSniff widget · yoursite.com",
      replayLabel: "Session replay",
      replayMeta: "42 frames · 00:42 · silent",
      timelineLabel: "Timeline",
      logsLabel: "Logs",
      consoleLabel: "Console",
      ticketLogTexts: [
        "→  Navigated to /checkout",
        "↖  Click on 'Checkout'",
        "⇅  GET /api/user · 200 OK",
        "⇅  GET /api/cart · 200 OK",
        "⇅  POST /api/apply-coupon · 206 Partial",
        "⇅  POST /api/checkout · 422 Unprocessable",
        "✕  TypeError: Cannot read properties of undefined (reading 'id')",
        "✕  Uncaught error in event handler",
      ],
    },
    howItWorks: {
      title: "How it works",
      subtitle: "Two paths, one dashboard. Pick what works for you — or use both.",
      scriptBadge: "<script>",
      scriptTitle: "For your site",
      testerBadge: "Chrome",
      testerTitle: "For your testers",
      scriptSteps: [
        { n: "01", title: "Paste the script", desc: "One line of code in your HTML. Zero additional setup." },
        { n: "02", title: "Visitor sees the widget", desc: 'A floating button appears in the corner: "Report a bug".' },
        { n: "03", title: "Reports with context", desc: "Session replay, network and console logs are captured automatically." },
        { n: "04", title: "Ticket on the dashboard", desc: "Dev opens the ticket and reproduces the bug on the first try." },
      ],
      testerSteps: [
        { n: "01", title: "Install the extension", desc: "Chrome extension available as a .zip — no Chrome Store required." },
        { n: "02", title: "Paste the API key", desc: "Dev generates the key on the dashboard and sends it to the tester. Setup in 30s." },
        { n: "03", title: "Browse and report", desc: "Record the full session. Select the bug segment on the timeline." },
        { n: "04", title: "Ticket on the dashboard", desc: "rrweb replay, network logs, console logs and metadata arrive together." },
      ],
    },
    problem: {
      title: "The bug arrives. The context doesn't.",
      subtitle: "Tester clicks, dev can't see. The cycle eats development hours that could go to features.",
      soundFamiliar: "Sound familiar?",
      stats: [
        { value: "30%", label: "of reported bugs", desc: "can't be reproduced by the dev who receives the report." },
        { value: "3×", label: "longer fix time", desc: "when the report arrives without network and console logs." },
        { value: "2–4h", label: "per sprint wasted", desc: "in \"can't reproduce\" loops between dev and tester." },
      ],
      painPoints: [
        '"I can\'t reproduce this bug"',
        '"Which browser version were you using?"',
        '"Can you record a video and send it?"',
        '"Which API call was it making?"',
        '"What was the error in the console?"',
        '"Can you give me the exact steps to reproduce?"',
      ],
    },
    dashboard: {
      title: "What lands on your dashboard",
      subtitle: "Every ticket has everything the dev needs to reproduce and fix — without asking anything else.",
      ticketTitle: "Checkout broken after address selection",
      replayLabel: "Replay",
      timelineLabel: "Event timeline",
      networkLabel: "Network logs",
      consoleLabel: "Console logs",
      metaLabel: "Metadata",
      metaRows: [
        ["Browser", "Chrome 131 / macOS 14"],
        ["Viewport", "1440 × 900"],
        ["URL", "/checkout?step=2"],
        ["Reported", "3 minutes ago"],
      ],
      timelineEvents: [
        { type: "click", label: "Click on 'Checkout'", t: "00:38" },
        { type: "network", label: "POST /api/checkout → 422", t: "00:39" },
        { type: "error", label: "TypeError: Cannot read 'id'", t: "00:39" },
        { type: "network", label: "GET /api/payment → 500", t: "00:40" },
        { type: "click", label: "Click on 'Try again'", t: "00:42" },
      ],
    },
    cta: {
      title: 'No more "I can\'t reproduce it"',
      subtitle:
        "BugSniff is in development. Join the waitlist and be notified when access opens — and help shape the product with your feedback.",
      button: "Join the waitlist",
    },
    footer: {
      waitlist: "Waitlist",
      email: "contato@bugsniff.com.br",
    },
    modal: {
      title: "Join the waitlist",
      subtitle: "We'll notify you when BugSniff opens.",
      successTitle: "You're on the list!",
      successDesc: "We'll email you as soon as BugSniff opens.\nThank you for your interest!",
      closeBtn: "Close",
      emailLabel: "Email",
      feedbackLabel: "What is your biggest challenge with bugs?",
      feedbackOptional: "(optional)",
      emailPlaceholder: "you@company.com",
      feedbackPlaceholder: "e.g. testers can't describe the context, non-reproducible bugs...",
      submitBtn: "Notify me when it's ready",
      submittingBtn: "Sending...",
      noSpam: "No spam. Just one notification when the product launches.",
      closeLabel: "Close",
      errorFallback: "Something went wrong. Please try again.",
      errorConnection: "Connection error. Check your internet and try again.",
    },
    widget: {
      hint: "click to simulate the flow",
      openTitle: "Close widget",
      closedTitle: "Open widget",
      readyLabel: "— ready to capture",
      reportPlaceholder: "e.g. Button doesn't work at checkout…",
      sendBtn: "Send report",
      capturingLabel: "Capturing screenshots…",
      capturingSub: "building silent replay",
      replayCaptured: "Replay captured",
      replayMeta: "silent · 42 frames",
      timelineLabel: "Timeline",
      logsLabel: "Logs",
      creatingLabel: "Creating ticket…",
      creatingSub: "attaching replay and logs",
      ticketLabel: "Checkout Page",
      sendTicketBtn: "Send",
      ticketCreated: "Ticket created!",
      ticketRef: "#tkt_7f2a · Checkout Page",
      ticketNote: "Silent replay attached automatically",
      logLabels: ["Click on checkout", "TypeError: Cannot read 'id'", "POST /api/checkout 422"],
    },
  },
};

export type Locale = keyof typeof content;
